version: '3.7'

services:
  maven:
    build:
      context: ./maven/
    volumes:
      - war:/STS/Eclipse

  mysql:
    build:
      context: ./mysql/
    ports:
      - "8514:8514"
  

volumes:
  war:
