FROM mysql:latest

RUN mysql && create database dd; && create user 'acp4pogynvaeidfj@'localhost' identified by 'jc31d2qyy7h9jv5jn1u9uosjksxzaizw'; && GRANT ALL PRIVILEGES ON dd.* to 'acp4pogynvaeidfj'@'localhost'; && FLUSH PRIVILEGES; && exit
